[sources.journald]
type = "journald"

[transforms.shape]
type = "remap"
inputs = ["journald"]
source = '''
.tenant_id = {{TENANT_ID}}
.source_id = "{{SOURCE_ID}}"
.message = string!(.message)
.source_type = "linux_journald"
'''

[sinks.http]
type = "http"
inputs = ["shape"]
uri = "{{BASE_URL}}/api/v2/ingest/ndjson"
encoding.codec = "ndjson"
method = "POST"
headers."Content-Type" = "application/x-ndjson"
headers."X-API-Key" = "{{API_KEY}}"
buffer.type = "disk"
buffer.max_size = 134217728 # 128 MiB
request.in_flight_limit = 16
batch.max_events = 500
batch.timeout_secs = 2
